from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

from .db import connect
from .compute import compute_stats
from .site import copy_static_site
from .validation import DatabaseValidationError, assert_exportable

# Keep in sync with frontend/site/assets/player-colors.js
_COLOR_PALETTE = [
  "#56B4E9","#E69F00","#009E73","#F0E442","#0072B2","#F8766D","#CC79A7","#00BFC4",
  "#F8766D","#7CAE00","#C77CFF","#A3A500","#8DD3C7","#FFFFB3","#BEBADA","#FB8072",
  "#80B1D3","#FDB462","#B3DE69","#FCCDE5","#BC80BD","#CCEBC5","#FFED6F","#9AD0F5",
]

def _normalize_player(name: str) -> str:
    return str(name or "").strip().lower()

def _build_player_color_overrides(commander_players: list[str], draft_players: list[str]) -> dict[str, str]:
    # Commander players get the first colors in deterministic (sorted) order.
    seen: set[str] = set()
    ordered: list[str] = []
    for p in sorted(commander_players, key=lambda s: _normalize_player(s)):
        k = _normalize_player(p)
        if k and k not in seen:
            seen.add(k); ordered.append(k)
    # Draft-only players get subsequent colors (also deterministic).
    for p in sorted(draft_players, key=lambda s: _normalize_player(s)):
        k = _normalize_player(p)
        if k and k not in seen:
            seen.add(k); ordered.append(k)
    out: dict[str, str] = {}
    for i, k in enumerate(ordered):
        out[k] = _COLOR_PALETTE[i % len(_COLOR_PALETTE)]
    return out

def _canonicalize_json_numbers(value):
    """Stabilize insignificant floating-point noise in exported JSON."""
    if isinstance(value, bool) or value is None or isinstance(value, (str, int)):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError(f"Non-finite float in export: {value!r}")
        out = float(f"{value:.14g}")
        return 0.0 if out == 0.0 else out
    if isinstance(value, list):
        return [_canonicalize_json_numbers(v) for v in value]
    if isinstance(value, dict):
        return {k: _canonicalize_json_numbers(v) for k, v in value.items()}
    return value


def _write_player_color_overrides_js(overrides: dict[str, str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # JS file consumed by frontend: defines window.PLAYER_COLOR_OVERRIDES
    lines = [
        "/* AUTO-GENERATED by backend exporter. Do not edit manually. */",
        "window.PLAYER_COLOR_OVERRIDES = window.PLAYER_COLOR_OVERRIDES || {};",
        "(function(){",
        "  const m = " + json.dumps(overrides, ensure_ascii=False, sort_keys=True) + ";",
        "  for (const k in m) { if (Object.prototype.hasOwnProperty.call(m, k)) window.PLAYER_COLOR_OVERRIDES[k] = m[k]; }",
        "})();",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")

def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="export_stats", description="Export static stats site (GitHub Pages friendly).")
    ap.add_argument("--db", required=True, help="Path to commander_tracker.sqlite")
    ap.add_argument("--draft-db", default=None, help="Optional path to draft_tracker.sqlite. If set, also writes docs/data/draft.v1.json")
    ap.add_argument("--docs", default="docs", help="Output docs directory (default: docs)")
    ap.add_argument("--site", default=None, help="Path to frontend/site (default: <repo>/frontend/site)")
    ap.add_argument(
        "--strict-duplicates",
        action="store_true",
        help="Fail export on every duplicate player, including configured legacy exceptions.",
    )
    ap.add_argument(
        "--validation-exceptions",
        default=None,
        help="JSON file with legacy validation exceptions (default: data/validation_exceptions.json).",
    )
    return ap

def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    repo_root = Path(__file__).resolve().parents[2]  # .../backend/commander_stats -> repo root
    site_dir = Path(args.site) if args.site else (repo_root / "frontend" / "site")
    docs_dir = Path(args.docs).resolve()

    # (Re)create static site root
    copy_static_site(str(site_dir), str(docs_dir))

    # Export JSON data
    data_dir = docs_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    db_path = Path(args.db).resolve()

    exceptions_path = (
        Path(args.validation_exceptions).resolve()
        if args.validation_exceptions
        else (repo_root / "data" / "validation_exceptions.json")
    )
    allowed_duplicate_game_ids: set[int] = set()
    if exceptions_path.exists():
        try:
            raw_exceptions = json.loads(exceptions_path.read_text(encoding="utf-8"))
            allowed_duplicate_game_ids = {
                int(v) for v in (raw_exceptions.get("duplicate_player_game_ids") or [])
            }
        except Exception as exc:
            raise SystemExit(f"File eccezioni validazione non valido: {exceptions_path}: {exc}")

    conn = connect(str(db_path))
    try:
        try:
            issues = assert_exportable(
                conn,
                duplicate_players_are_errors=args.strict_duplicates,
                allowed_duplicate_game_ids=allowed_duplicate_game_ids,
            )
        except DatabaseValidationError as exc:
            details = "\n".join(f"  - [{i.code}] {i.message}" for i in exc.issues)
            raise SystemExit("Commander DB non esportabile:\n" + details)
        for issue in issues:
            if issue.severity == "warning":
                print(f"WARNING [{issue.code}] {issue.message}", file=sys.stderr)

        # generated_utc is computed deterministically from DB content when omitted
        stats = _canonicalize_json_numbers(compute_stats(conn, generated_utc=None))
    finally:
        conn.close()

    json_path = data_dir / "stats.v1.json"

    # Always write the JSON file. The output is now deterministic for an
    # unchanged DB (including generated_utc).
    new_json = json.dumps(stats, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    json_path.write_text(new_json, encoding="utf-8")

    # Export JSON schema alongside the data for a visible contract
    schema_src = repo_root / "backend" / "stats.v1.schema.json"
    if schema_src.exists():
        (data_dir / "stats.v1.schema.json").write_text(schema_src.read_text(encoding="utf-8"), encoding="utf-8")

    draft_data = None
    # Optional: draft export into the same docs output (separate DB for safety)
    if args.draft_db:
        try:
            from draft_stats.compute import compute_draft, write_json  # type: ignore
        except Exception as e:
            raise SystemExit(f"Draft export requested but draft_stats not importable: {e}")

        draft_data = compute_draft(str(Path(args.draft_db).resolve()))
        write_json(draft_data, str(data_dir / "draft.v1.json"))

    # --- Player color overrides (static mapping shared across pages) ---
    # Draft, Stats, Meta-profile, etc. all read window.PLAYER_COLOR_OVERRIDES (if present).
    # This keeps player colors consistent across the whole site and across runs.
    commander_players = [str(r.get("player") or "").strip() for r in (stats.get("by_player") or []) if isinstance(r, dict)]
    draft_players = []
    if isinstance(draft_data, dict):
        dp = draft_data.get("by_player")
        if isinstance(dp, dict):
            draft_players = [str(k).strip() for k in dp.keys() if str(k).strip()]
        elif isinstance(dp, list):
            # future-proofing in case schema changes
            draft_players = [str(r.get("player") or "").strip() for r in dp if isinstance(r, dict)]

    overrides = _build_player_color_overrides(commander_players, draft_players)
    _write_player_color_overrides_js(overrides, docs_dir / "assets" / "player-color-overrides.js")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
